/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TasbihCounter = IDL.Record({
  'name' : IDL.Text,
  'count' : IDL.Nat,
  'target' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PrayerSettings = IDL.Record({
  'latitude' : IDL.Float64,
  'notificationsEnabled' : IDL.Bool,
  'calculationMethod' : IDL.Text,
  'longitude' : IDL.Float64,
  'madhab' : IDL.Text,
  'locationName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateTasbihCounter' : IDL.Func([TasbihCounter], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTasbihCounter' : IDL.Func([IDL.Text], [], []),
  'getCallerPrayerSettings' : IDL.Func(
      [],
      [IDL.Opt(PrayerSettings)],
      ['query'],
    ),
  'getCallerTasbihCounters' : IDL.Func([], [IDL.Vec(TasbihCounter)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPrayerSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PrayerSettings)],
      ['query'],
    ),
  'getTasbihCounters' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TasbihCounter)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementTasbihCounter' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetTasbihCounter' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePrayerSettings' : IDL.Func([PrayerSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TasbihCounter = IDL.Record({
    'name' : IDL.Text,
    'count' : IDL.Nat,
    'target' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PrayerSettings = IDL.Record({
    'latitude' : IDL.Float64,
    'notificationsEnabled' : IDL.Bool,
    'calculationMethod' : IDL.Text,
    'longitude' : IDL.Float64,
    'madhab' : IDL.Text,
    'locationName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateTasbihCounter' : IDL.Func([TasbihCounter], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTasbihCounter' : IDL.Func([IDL.Text], [], []),
    'getCallerPrayerSettings' : IDL.Func(
        [],
        [IDL.Opt(PrayerSettings)],
        ['query'],
      ),
    'getCallerTasbihCounters' : IDL.Func(
        [],
        [IDL.Vec(TasbihCounter)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPrayerSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PrayerSettings)],
        ['query'],
      ),
    'getTasbihCounters' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TasbihCounter)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementTasbihCounter' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetTasbihCounter' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePrayerSettings' : IDL.Func([PrayerSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };